### ISSUE TITLE
Option on cleaning reactions

### ISSUE THREAD

**Issue by avurro** [ygimenez/Pagination-Utils#10]
**Is your feature request related to a problem? Please describe.**
Users would like to have the freedom to add emojis on embeds.

**Describe the solution you'd like**
An option that allows you to define its behavior.

**Comment by ygimenez** [comment]
Do you mean using custom emotes on buttons? If yes, `Pages.buttonize()` do exactly that, allowing you to bind an action to a button (which is defined by you)

**Comment by avurro** [comment]
![image](https://user-images.githubusercontent.com/2487392/106613670-c0c4e500-656a-11eb-8321-2268688b1463.png)
Users don't have the freedom to add their own emojis under this embed, because they are automatically removed. Is it possible to allow them to be kept?

**Comment by ygimenez** [comment]
That's something you need to do on your side, just store the Map of buttons in a variable and regenerate the buttons each time someone adds a reaction to the Map.

I do something similar on my bot and it works quite well, but this isn't possible library-wise because once called all methods are final.

**Comment by ygimenez** [comment]
Not exactly what you wanted, but reaction removal is now optional in [release 2.1.1](https://github.com/ygimenez/Pagination-Utils/tree/2.1.1)
