### ISSUE TITLE
Labels instead of emojis

### ISSUE THREAD

**Issue by Cabbasca** [ygimenez/Pagination-Utils#50]
**Is your feature request related to a problem? Please describe.**
I want to be able to not use emojis and just use text when using buttons for pagination

**Describe the solution you'd like**
Adding the ability to use labels too

**Describe alternatives you've considered**
I have tried to put the labels as emojis and that didn't really work

**Additional context**

**Comment by ygimenez** [comment]
I'll see whether it's possible to implement

**Comment by ygimenez** [comment]
Sadly, after analyzing the current state of the library, it relies a lot on emotes (partly due to reaction support) so adding support for emoteless buttons would require extensive changes on how events are processed.

This might become possible in a future major release, but for the meantime, this cannot be added.
